//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SOFTPLUSPROJECT.Models.tbl_ItemSize), "tbl_DetailInfo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SOFTPLUSPROJECT.Models.tbl_DetailInfo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SOFTPLUSPROJECT.Models.tbl_MasterDetailInfo), "tbl_DetailInfo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SOFTPLUSPROJECT.Models.tbl_DetailInfo))]

// Original file name:
// Generation date: 7/6/2013 4:57:49 PM
namespace SOFTPLUSPROJECT.Models
{
    
    /// <summary>
    /// There are no comments for SoftplusTextingEntities in the schema.
    /// </summary>
    public partial class SoftplusTextingEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SoftplusTextingEntities object using the connection string found in the 'SoftplusTextingEntities' section of the application configuration file.
        /// </summary>
        public SoftplusTextingEntities() : 
                base("name=SoftplusTextingEntities", "SoftplusTextingEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SoftplusTextingEntities object.
        /// </summary>
        public SoftplusTextingEntities(string connectionString) : 
                base(connectionString, "SoftplusTextingEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SoftplusTextingEntities object.
        /// </summary>
        public SoftplusTextingEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SoftplusTextingEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tbl_DetailInfo in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tbl_DetailInfo> tbl_DetailInfo
        {
            get
            {
                if ((this._tbl_DetailInfo == null))
                {
                    this._tbl_DetailInfo = base.CreateQuery<tbl_DetailInfo>("[tbl_DetailInfo]");
                }
                return this._tbl_DetailInfo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tbl_DetailInfo> _tbl_DetailInfo;
        /// <summary>
        /// There are no comments for tbl_ItemSize in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tbl_ItemSize> tbl_ItemSize
        {
            get
            {
                if ((this._tbl_ItemSize == null))
                {
                    this._tbl_ItemSize = base.CreateQuery<tbl_ItemSize>("[tbl_ItemSize]");
                }
                return this._tbl_ItemSize;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tbl_ItemSize> _tbl_ItemSize;
        /// <summary>
        /// There are no comments for tbl_MasterDetailInfo in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tbl_MasterDetailInfo> tbl_MasterDetailInfo
        {
            get
            {
                if ((this._tbl_MasterDetailInfo == null))
                {
                    this._tbl_MasterDetailInfo = base.CreateQuery<tbl_MasterDetailInfo>("[tbl_MasterDetailInfo]");
                }
                return this._tbl_MasterDetailInfo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tbl_MasterDetailInfo> _tbl_MasterDetailInfo;
        /// <summary>
        /// There are no comments for tbl_DetailInfo in the schema.
        /// </summary>
        public void AddTotbl_DetailInfo(tbl_DetailInfo tbl_DetailInfo)
        {
            base.AddObject("tbl_DetailInfo", tbl_DetailInfo);
        }
        /// <summary>
        /// There are no comments for tbl_ItemSize in the schema.
        /// </summary>
        public void AddTotbl_ItemSize(tbl_ItemSize tbl_ItemSize)
        {
            base.AddObject("tbl_ItemSize", tbl_ItemSize);
        }
        /// <summary>
        /// There are no comments for tbl_MasterDetailInfo in the schema.
        /// </summary>
        public void AddTotbl_MasterDetailInfo(tbl_MasterDetailInfo tbl_MasterDetailInfo)
        {
            base.AddObject("tbl_MasterDetailInfo", tbl_MasterDetailInfo);
        }
    }
    /// <summary>
    /// There are no comments for SoftplusTextingModel.tbl_DetailInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// ItemSizeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SoftplusTextingModel", Name="tbl_DetailInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tbl_DetailInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tbl_DetailInfo object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="itemSizeID">Initial value of ItemSizeID.</param>
        public static tbl_DetailInfo Createtbl_DetailInfo(int customerID, int itemSizeID)
        {
            tbl_DetailInfo tbl_DetailInfo = new tbl_DetailInfo();
            tbl_DetailInfo.CustomerID = customerID;
            tbl_DetailInfo.ItemSizeID = itemSizeID;
            return tbl_DetailInfo;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this.ReportPropertyChanging("CustomerID");
                this._CustomerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomerID");
                this.OnCustomerIDChanged();
            }
        }
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property ItemSizeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemSizeID
        {
            get
            {
                return this._ItemSizeID;
            }
            set
            {
                this.OnItemSizeIDChanging(value);
                this.ReportPropertyChanging("ItemSizeID");
                this._ItemSizeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemSizeID");
                this.OnItemSizeIDChanged();
            }
        }
        private int _ItemSizeID;
        partial void OnItemSizeIDChanging(int value);
        partial void OnItemSizeIDChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<float> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this.ReportPropertyChanging("Quantity");
                this._Quantity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Quantity");
                this.OnQuantityChanged();
            }
        }
        private global::System.Nullable<float> _Quantity;
        partial void OnQuantityChanging(global::System.Nullable<float> value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for tbl_ItemSize in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public tbl_ItemSize tbl_ItemSize
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_ItemSize>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_ItemSize>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for tbl_ItemSize in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<tbl_ItemSize> tbl_ItemSizeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_ItemSize>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<tbl_ItemSize>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_ItemSize", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for tbl_MasterDetailInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public tbl_MasterDetailInfo tbl_MasterDetailInfo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_MasterDetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_MasterDetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for tbl_MasterDetailInfo in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<tbl_MasterDetailInfo> tbl_MasterDetailInfoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_MasterDetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<tbl_MasterDetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_MasterDetailInfo", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SoftplusTextingModel.tbl_ItemSize in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemSizeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SoftplusTextingModel", Name="tbl_ItemSize")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tbl_ItemSize : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tbl_ItemSize object.
        /// </summary>
        /// <param name="itemSizeID">Initial value of ItemSizeID.</param>
        /// <param name="itemSize">Initial value of ItemSize.</param>
        public static tbl_ItemSize Createtbl_ItemSize(int itemSizeID, int itemSize)
        {
            tbl_ItemSize tbl_ItemSize = new tbl_ItemSize();
            tbl_ItemSize.ItemSizeID = itemSizeID;
            tbl_ItemSize.ItemSize = itemSize;
            return tbl_ItemSize;
        }
        /// <summary>
        /// There are no comments for Property ItemSizeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemSizeID
        {
            get
            {
                return this._ItemSizeID;
            }
            set
            {
                this.OnItemSizeIDChanging(value);
                this.ReportPropertyChanging("ItemSizeID");
                this._ItemSizeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemSizeID");
                this.OnItemSizeIDChanged();
            }
        }
        private int _ItemSizeID;
        partial void OnItemSizeIDChanging(int value);
        partial void OnItemSizeIDChanged();
        /// <summary>
        /// There are no comments for Property ItemSize in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemSize
        {
            get
            {
                return this._ItemSize;
            }
            set
            {
                this.OnItemSizeChanging(value);
                this.ReportPropertyChanging("ItemSize");
                this._ItemSize = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemSize");
                this.OnItemSizeChanged();
            }
        }
        private int _ItemSize;
        partial void OnItemSizeChanging(int value);
        partial void OnItemSizeChanged();
        /// <summary>
        /// There are no comments for tbl_DetailInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_DetailInfo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tbl_DetailInfo> tbl_DetailInfo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tbl_DetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_DetailInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tbl_DetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_DetailInfo", "tbl_DetailInfo", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SoftplusTextingModel.tbl_MasterDetailInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomerID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SoftplusTextingModel", Name="tbl_MasterDetailInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tbl_MasterDetailInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tbl_MasterDetailInfo object.
        /// </summary>
        /// <param name="customerID">Initial value of CustomerID.</param>
        /// <param name="customerName">Initial value of CustomerName.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="loadDate">Initial value of LoadDate.</param>
        public static tbl_MasterDetailInfo Createtbl_MasterDetailInfo(int customerID, string customerName, string address, global::System.DateTime loadDate)
        {
            tbl_MasterDetailInfo tbl_MasterDetailInfo = new tbl_MasterDetailInfo();
            tbl_MasterDetailInfo.CustomerID = customerID;
            tbl_MasterDetailInfo.CustomerName = customerName;
            tbl_MasterDetailInfo.Address = address;
            tbl_MasterDetailInfo.LoadDate = loadDate;
            return tbl_MasterDetailInfo;
        }
        /// <summary>
        /// There are no comments for Property CustomerID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this.OnCustomerIDChanging(value);
                this.ReportPropertyChanging("CustomerID");
                this._CustomerID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomerID");
                this.OnCustomerIDChanged();
            }
        }
        private int _CustomerID;
        partial void OnCustomerIDChanging(int value);
        partial void OnCustomerIDChanged();
        /// <summary>
        /// There are no comments for Property CustomerName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this._CustomerName;
            }
            set
            {
                this.OnCustomerNameChanging(value);
                this.ReportPropertyChanging("CustomerName");
                this._CustomerName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CustomerName");
                this.OnCustomerNameChanged();
            }
        }
        private string _CustomerName;
        partial void OnCustomerNameChanging(string value);
        partial void OnCustomerNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property LoadDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LoadDate
        {
            get
            {
                return this._LoadDate;
            }
            set
            {
                this.OnLoadDateChanging(value);
                this.ReportPropertyChanging("LoadDate");
                this._LoadDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LoadDate");
                this.OnLoadDateChanged();
            }
        }
        private global::System.DateTime _LoadDate;
        partial void OnLoadDateChanging(global::System.DateTime value);
        partial void OnLoadDateChanged();
        /// <summary>
        /// There are no comments for tbl_DetailInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SoftplusTextingModel", "FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_DetailInfo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tbl_DetailInfo> tbl_DetailInfo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tbl_DetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_DetailInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tbl_DetailInfo>("SoftplusTextingModel.FK_tbl_DetailInfo_tbl_MasterDetailInfo", "tbl_DetailInfo", value);
                }
            }
        }
    }
}
